config/routes.rb
Rails.application.routes.draw do

  resources :hospitals, only: %i[index show]
  resources :pharmacies, only: [:index, :show]
  root to: 'toppages#index'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :pharmacy_to_hospitals, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital_to_pharmacy.rb
class HospitalToPharmacy < ApplicationRecord
end

app/models/pharmacy_to_hospital.rb
class PharmacyToHospital < ApplicationRecord
  belongs_to :pharmacy, class_name: 'User'
  belongs_to :hospital, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :role, presence: true
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  validates :bio, presence: true, length: {maximum: 500}
  validates :password, presence: true
  validates :price, presence: true
  has_secure_password
  mount_uploader :image, ImageUploader

  has_many :hospital_to_pharmacies, foreign_key: 'hospital_id'
  has_many :pharmacy_to_hospitals, foreign_key: 'pharmacy_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_admin_logged_in
    if !logged_in? || current_user.role != 'Admin'
      flash[:danger] = '権限がありません'
      redirect_to root_path
    end
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = User.where(role: 'Hospital').page(params[:page])
  end

  def show
    #対象外のidを指定するとエラー画面が出る
    @hospital = User.where(role: 'Hospital').find(params[:id])
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  def index
    @hospitals = User.where(role: 'Hospital').page(params[:page])
  end

  def show
    #対象外のidを指定するとエラー画面が出る
    @hospital = User.where(role: 'Hospital').find(params[:id])
  end

  def like_to
    
  end
end

app/controllers/pharmacy_to_hospitals_controller.rb
class PharmacyToHospitalsController < ApplicationController
  def create
    @pharmacy = PharmacyToHospital.new(hospital_id: params[:id], pharmacy_id: session[:user_id])
    if @pharmacy.save
      redirect_to pharmacy_path, notice: 'Succeed'
    else
      flash[:error] = @pharmacy.errors.full_messages
      render :'pharmacies/show'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #byebug
    email = params[:email]
    password = params[:password]
    if login(email, password)
      flash[:success] = "#{session[:user_name]}様のログインに成功しました"
      case
      when session[:role] == 'Admin'
        redirect_to users_path
      when session[:role] == 'Pharmacy'
        redirect_to hospitals_path
      end
    else
      flash[:danger] = 'Emailかパスワードが間違っています'
      render 'sessions/new'
    end
  end

  def destroy
    session[:user_id] = nil
    session[:role] = nil
    session[:user_name] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

  def login(email, password)
    #byebug
    @user = User.find_by(email: email)
    if @user&.authenticate(password)
      session[:user_id] = @user.id
      session[:user_name] = @user.name
      # if @user.role == 'Admin'
      #   session[:role] = 'Admin'
      # end
      case
      when @user.role == 'Admin' then
        session[:role] = 'Admin'
      when @user.role == 'Hospital' then
        session[:role] = 'Hospital'
      when @user.role == 'Pharmacy' then
        session[:role] = 'Pharmacy'
      end
      true
    else
      false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin_logged_in, only: %i[index edit new create]
  def index
    @users = User.where("(role = ?) OR (role = ?)", 'Hospital', 'Pharmacy').page(params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:succeed] = 'ユーザが作成されました'
      redirect_to root_path
    else
      flash[:error] = 'ユーザの作成に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: "#{@user.name}を更新しました"
    else
      flash[:alert] = "#{@user.name}の更新に失敗しました"
      render :edit
    end
  end

  def destroy
    #byebug
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :role, :bio)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/helpers/pharmacy_to_hospitals_helper.rb
module PharmacyToHospitalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hospitals/index.html.erb
<h1>Hospitals#index</h1>
<p>Find me in app/views/hospitals/index.html.erb</p>
<table class="table table-striped">
  <thead>
  <th>id</th>
  <th>name</th>
  <th>email</th>
  <th>role</th>
  <th></th>
  </thead>
  <tr>
    <tbody>
    <% @hospitals.each do |hospital|%>
      <tr>
        <td><%=hospital.id %></td>
        <td><%=hospital.name %></td>
        <td><%=hospital.email %></td>
        <td><%=hospital.role %></td>
        <td><%= link_to '詳細', pharmacy_path(hospital)  %></td>
      </tr>
    <% end %>
    </tbody>
</table>
<br>
<div class="offset-md-4 col-md-4"><%= paginate @hospitals %></div>

app/views/hospitals/show.html.erb
<h1>Hospitals#show</h1>
<p>Find me in app/views/hospitals/show.html.erb</p>

<div class="row">
  <div class="col-md-4">
    <% if @hospital.image_url %>
      <%= image_tag @hospital.image_url, class: 'photo1'%>
    <% end %>
  </div>
  <div class="col-md-8">
    <table class="table table-striped">
      <tr>
        <th>名称</th>
        <td><%= @hospital.name %></td>
      </tr>
      <tr>
        <th>提示金額</th>
        <td ><%= (number_with_delimiter(@hospital.price)).to_s + '円' %></td>
      </tr>
      <tr>
        <th>所在地</th>
        <td><%= @hospital.place %></td>
      </tr>
      <tr>
        <th>備考</th>
        <td><%= @hospital.bio %></td>
      </tr>
    </table>
    <%= button_to 'お気に入り', pharmacy_to_hospitals_path, method: get, params: {id: @hospital.id}%>
  </div>
</div>
<br>
<%= link_to '>戻る', pharmacies_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Relashionship</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="container">
  <div class="header">
    <h1 class="text-left">H & P</h1>
  </div>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <% if session[:role] == 'Admin' %>
  <%= link_to 'Create user',  new_user_path, class: 'btn btn-danger' %>
  <%= link_to 'User List', users_path, class: 'btn btn-danger' %>
  <% end %>
  <% if session[:user_id].present? %>
    <%= link_to 'logout', logout_path, method: :delete, class: 'btn btn-primary'%>
  <% else %>
    <%= link_to 'login', login_path, class: 'btn btn-success'%>
  <% end %>
    <%= yield %>
</div>
  </body>
</html>

app/views/pharmacies/index.html.erb
<h1>Pharmacies#index</h1>
<p>Find me in app/views/pharmacies/index.html.erb</p>
<table class="table table-striped">
  <thead>
  <th>id</th>
  <th>name</th>
  <th>email</th>
  <th>role</th>
  <th></th>
  </thead>
  <tr>
    <tbody>
    <% @hospitals.each do |hospital|%>
      <tr>
        <td><%=hospital.id %></td>
        <td><%=hospital.name %></td>
        <td><%=hospital.email %></td>
        <td><%=hospital.role %></td>
        <td><%= link_to '詳細', pharmacy_path(hospital)  %></td>
      </tr>
    <% end %>
    </tbody>
</table>
<br>
<div class="offset-md-4 col-md-4"><%= paginate @hospitals %></div>

app/views/pharmacies/show.html.erb
<h1>Pharmacies#show</h1>
<p>Find me in app/views/pharmacies/show.html.erb</p>

<div class="row">
<div class="col-md-4">
  <% if @hospital.image_url %>
   <%= image_tag @hospital.image_url, class: 'photo1'%>
  <% end %>
</div>
<div class="col-md-8">
  <table class="table table-striped">
      <tr>
         <th>名称</th>
         <td><%= @hospital.name %></td>
      </tr>
      <tr>
        <th>提示金額</th>
        <td ><%= (number_with_delimiter(@hospital.price)).to_s + '円' %></td>
      </tr>
      <tr>
         <th>所在地</th>
         <td><%= @hospital.place %></td>
      </tr>
      <tr>
         <th>備考</th>
         <td><%= @hospital.bio %></td>
      </tr>
  </table>
  <%= button_to 'お気に入り', pharmacy_to_hospitals_path %>
</div>
</div>
<br>
<%= link_to '>戻る', pharmacies_path  %>

app/views/toppages/index.html.erb
<h1>Toppages#index</h1>
<p>Find me in app/views/toppages/index.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user, local: true do |f| %>
  <%= f.text_field :name, placeholder: '名前' %>
  <%= f.text_field :email, placeholder: 'Email' %>

  <%= f.file_field :image, class: 'preview' %>
  <br>
  <%= f.password_field :password, placeholder: 'パスワード' %>
  <%= f.text_field :price, placeholder: '提示価格'  %>
  <br>
  <%= f.select :place, [['東京', '東京'], ['神奈川', '神奈川'], ['埼玉', '埼玉'], ['茨城', '茨城'], ['千葉', '千葉']]  %>
  <%= f.text_area :bio, placeholder: '紹介文を書いてください'  %>
  <br>
  <%= f.submit '更新', data: { disable_with: "更新中..." } %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<table class="table table-striped">
  <thead>
    <th>id</th>
    <th>name</th>
    <th>email</th>
    <th>role</th>
    <th></th>
    <th></th>
  </thead>
  <tr>
  <tbody>
<% @users.each do |user|%>
  <tr>
    <td><%=user.id %></td>
    <td><%=user.name %></td>
    <td><%=user.email %></td>
    <td><%=user.role %></td>
    <td><%= link_to 'Edit', edit_user_path(user)  %></td>
    <td><%= link_to 'Delete', user_path(user), method: :delete,
                    data: { confirm: "#{user.name}を削除してもよろしいですか？"}  %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<br>
<div class="offset-md-4 col-md-4"><%= paginate @users %></div>

app/views/users/new.html.erb
<h1>Users#new</h1>

<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user, local: true do |f| %>
  <%= f.radio_button :role, 'Admin'  %>
  <%= f.label :role, '管理者', value: 'Admin'  %>
  <%= f.radio_button :role, 'Hospital'  %>
  <%= f.label :role, '病院', value: 'Hospital'  %>
  <%= f.radio_button :role, 'Pharmacy'  %>
  <%= f.label :role, '薬局', value: 'Pharmacy'  %>
  <br>
  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.text_field :email, placeholder: 'email' %>

  <%= f.file_field :image, class: 'preview' %>
  <br>
  <%= f.password_field :password, placeholder: 'password' %>
  <%= f.text_area :bio, placeholder: 'Input your bio'  %>
  <%= f.submit '登録', data: { disable_with: "登録中..." } %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>